# homelab-platform/environments/dev/02-platform-services/values/values-eck-operator.yaml
installCRDs: true

managedNamespaces: 
  - elastic-system

resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 1000m
    memory: 512Mi

webhook:
  enabled: true