# External Secrets Operator Values
installCRDs: true

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Enable cert controller for webhook certificates
certController:
  create: true
  
# Webhook configuration
webhook:
  create: true
  port: 9443
  
# Service monitor for Prometheus (if you have monitoring)
serviceMonitor:
  enabled: true
  
# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

podSecurityContext:
  fsGroup: 1000