# Bitnami Keycloak Values
auth:
  valueFromRef:
    secretKeyRef:
      name: keycloak-secret
      usernameSecretKey: adminUser
      passwordSecretKey: adminPassword
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

replicaCount: 1

service:
  type: ClusterIP
  
postgresql:
  enabled: true

  auth:
    secretName: postgresql-secret
    postgresPassword: postgresPassword
    username: username
    password: password
    database: database

  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

ingress:
  enabled: false  # We'll use Istio Gateway instead