# HashiCorp Vault Values
global:
  enabled: true
  tlsDisable: true

server:
  enabled: true
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  
  # Dev mode - single instance
  dev:
    enabled: true
    devRootToken: "dev-only-token"
  
  dataStorage:
    enabled: true
    size: 5Gi
  
  standalone:
    enabled: true
  
  ha:
    enabled: false

ui:
  enabled: true
  serviceType: "ClusterIP"

injector:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 250m