# homelab-platform/environments/dev/02-platform-services/values/values-eck-operator.yaml
managedNamespaces: ["elastic-system"]

installCRDs: true

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 1000m
    memory: 512Mi

# Enable webhooks for validation
webhook:
  enabled: true