# File: environments/dev/01-infrastructure/values/values-istiod.yaml
global:
  meshID: dev-mesh
  multiCluster:
    clusterName: dev-cluster
  network: dev-network
  istioNamespace: istio-system

# Disable ingress gateway in istiod chart
gateways:
  istio-ingressgateway:
    enabled: false

pilot:
  image: pilot
  tag: 1.20.1
  hub: docker.io/istio
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  env:
    EXTERNAL_ISTIOD: false
    PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true

revision: ""