
# File: environments/dev/01-infrastructure/values/values-istiod.yaml
global: # Istio Control Plane Values
  meshID: dev-mesh
  multiCluster:
    clusterName: dev-cluster
  network: dev-network
  istioNamespace: istio-system

pilot:
  # Explicitly set image to avoid "auto" default
  image: pilot
  tag: 1.20.1
  hub: docker.io/istio
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  env:
    EXTERNAL_ISTIOD: false
    PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true

# Ensure istiod waits for base to be ready
revision: ""