# File: homelab-platform/environments/dev/01-infrastructure/values/values-istio-base.yaml
defaultRevision: default

global:
  istioNamespace: istio-system

base:
  enableCRDTemplates: true
  
crds:
  install: true