apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: bookmarks
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
  - secretKey: adminUser
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/keycloak
      metadataPolicy: None
      property: adminUser

  - secretKey: adminPassword
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/keycloak
      metadataPolicy: None
      property: adminPassword