apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-config
  namespace: bookmarks
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
  - secretKey: postgresPassword
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: postgresPassword
  
  - secretKey: username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: username

  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: password  

  - secretKey: database
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: database
