# Platform Services Application
# Layer 2: Platform services (Vault, Keycloak, Gateways)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/T-Py-T/homelab-platform
    targetRevision: HEAD
    path: environments/dev/02-platform-services
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - SkipDryRunOnMissingResource=true  # Skip validation if CRDs not ready
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Health checks for platform services
  ignoreDifferences:
  - group: networking.istio.io
    kind: Gateway
    jsonPointers:
    - /spec/selector