apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Platform Services Layer - Services that depend on infrastructure
# Deploy SECOND, after infrastructure is ready

helmCharts:
  # Istio Gateway - depends on istiod being ready
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.20.1
    releaseName: istio-ingressgateway
    namespace: istio-ingress
    valuesFile: values/values-istio-gateway.yaml

  # HashiCorp Vault - Secrets management
  - name: vault
    namespace: vault
    releaseName: vault
    repo: https://helm.releases.hashicorp.com
    valuesFile: values/values-vault.yaml
    version: 0.27.0

  # External Secrets Operator - Vault integration
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.11
    releaseName: external-secrets
    namespace: external-secrets-system
    valuesFile: values/values-external-secrets.yaml

  # Keycloak - Authentication and authorization
  - name: keycloak
    namespace: keycloak
    releaseName: keycloak
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values/values-keycloak.yaml
    version: 17.3.1

  # Elastic Cloud on Kubernetes - Logging and monitoring
  - name: eck-operator
    namespace: elastic-system
    releaseName: eck-operator
    repo: https://helm.elastic.co
    valuesFile: values/values-eck-operator.yaml
    version: 2.9.0

  # Kyverno - Policy engine
  - name: kyverno
    namespace: kyverno
    releaseName: kyverno
    repo: https://kyverno.github.io/kyverno
    valuesFile: values/values-kyverno.yaml
    version: 3.1.4

resources:
  - istio-gateways.yaml  # Istio Gateways - Depend on Istio being ready
  - vault-setup.yaml  # Vault configuration - Depends on Vault being deployed
  - external-secrets-store.yaml # External Secrets configuration - Depends on both Vault and ESO
  - external-secrets/keycloak-secret.yaml

labels:
- includeSelectors: true
  pairs:
    component: platform-services
    environment: dev
    managed-by: argocd
    layer: "02-platform-services"