apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Platform Services Layer - Services that depend on infrastructure
# Deploy SECOND, after infrastructure is ready

helmCharts:
# HashiCorp Vault - Secrets management
- name: vault
  namespace: vault
  releaseName: vault
  repo: https://helm.releases.hashicorp.com
  valuesFile: values/values-vault.yaml
  version: 0.27.0

# External Secrets Operator - Vault integration
- name: external-secrets
  namespace: external-secrets-system
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
  valuesFile: values/values-external-secrets.yaml
  version: 0.9.11

# Keycloak - Authentication and authorization
- name: keycloak
  namespace: keycloak
  releaseName: keycloak
  repo: https://charts.bitnami.com/bitnami
  valuesFile: values/values-keycloak.yaml
  version: 17.3.1

# Elastic Cloud on Kubernetes - Logging and monitoring
- name: eck-operator
  namespace: elastic-system
  releaseName: eck-operator
  repo: https://helm.elastic.co
  valuesFile: values/values-eck-operator.yaml
  version: 2.10.0

# Kyverno - Policy engine
- name: kyverno
  namespace: kyverno
  releaseName: kyverno
  repo: https://kyverno.github.io/kyverno
  valuesFile: values/values-kyverno.yaml
  version: 3.1.4

resources:
# Istio Gateways - Depend on Istio being ready
- istio-gateways.yaml
# Vault configuration - Depends on Vault being deployed
- vault-setup.yaml
# External Secrets configuration - Depends on both Vault and ESO
- external-secrets-store.yaml

labels:
- includeSelectors: true
  pairs:
    component: platform-services
    environment: dev
    managed-by: argocd
    layer: "02-platform-services"