# File: environments/dev/01-infrastructure/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

helmCharts:
  # Istio Base - CRDs and base components
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.20.1
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
    valuesFile: values/values-istio-base.yaml

  # Istio Control Plane
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.20.1
    releaseName: istiod
    namespace: istio-system
    valuesFile: values/values-istiod.yaml

  # Istio Ingress Gateway
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.20.1
    releaseName: istio-ingressgateway
    namespace: istio-ingress
    valuesFile: values/values-istio-gateway.yaml

labels:
  - includeSelectors: true
    pairs:
      component: infrastructure
      environment: dev
      managed-by: argocd
      layer: "01-infrastructure"