# Cilium LoadBalancer IP Pool Configuration
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
spec:
  cidrs:
  - cidr: "192.168.1.240/28"  # Adjust to your network
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam: "default-pool"

---
apiVersion: "cilium.io/v2alpha1" 
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
spec:
  serviceSelector: {}
  nodeSelector: {}
  interfaces:
  - "^eth[0-9]+"  # Adjust to your interface names
  externalIPs: true
  loadBalancerIPs: true