apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    istio-injection: disabled